FROM node:alpine3.10

WORKDIR /app

COPY package.json ./
RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]

# docker run -it -p 3000:3000 CONTAINER_ID 
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app 60cda096f8b8
#       web:
#        stdin_open: true